### ISSUE TITLE
Resolve dependency issues to bump virtualenv-clone from 0.5.4 to 0.5.7

### ISSUE THREAD

**Issue by BenMMcLean** [TechlauncherFireApp/backend#75]
See #71

**Comment by BenMMcLean** [comment]
Execution fails with following output:
```
﻿fireapp30-backend-fireapp-1  | [2023-08-22 12:50:54 +0000] [1] [INFO] Starting gunicorn 21.2.0
fireapp30-backend-fireapp-1  | [2023-08-22 12:50:54 +0000] [1] [DEBUG] Arbiter booted
fireapp30-backend-fireapp-1  | [2023-08-22 12:50:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
fireapp30-backend-fireapp-1  | [2023-08-22 12:50:54 +0000] [1] [INFO] Using worker: gthread
fireapp30-backend-fireapp-1  | [2023-08-22 12:50:54 +0000] [11] [INFO] Booting worker with pid: 11
fireapp30-backend-fireapp-1  | [2023-08-22 12:50:54 +0000] [13] [INFO] Booting worker with pid: 13
fireapp30-backend-fireapp-1  | [2023-08-22 12:50:54 +0000] [1] [DEBUG] 2 workers
fireapp30-backend-fireapp-1  | [2023-08-22 12:51:00 +0000] [11] [ERROR] Exception in worker process
fireapp30-backend-fireapp-1  | Traceback (most recent call last):
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
fireapp30-backend-fireapp-1  |     worker.init_process()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 95, in init_process
fireapp30-backend-fireapp-1  |     super().init_process()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
fireapp30-backend-fireapp-1  |     self.load_wsgi()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
fireapp30-backend-fireapp-1  |     self.wsgi = self.app.wsgi()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
fireapp30-backend-fireapp-1  |     self.callable = self.load()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
fireapp30-backend-fireapp-1  |     return self.load_wsgiapp()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
fireapp30-backend-fireapp-1  |     return util.import_app(self.app_uri)
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 371, in import_app
fireapp30-backend-fireapp-1  |     mod = importlib.import_module(module)
fireapp30-backend-fireapp-1  |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
fireapp30-backend-fireapp-1  |     return _bootstrap._gcd_import(name[level:], package, level)
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
fireapp30-backend-fireapp-1  |   File "/app/application.py", line 3, in <module>
fireapp30-backend-fireapp-1  |     from controllers import *
fireapp30-backend-fireapp-1  |   File "/app/controllers/__init__.py", line 21, in <module>
fireapp30-backend-fireapp-1  |     from .user import user_bp
fireapp30-backend-fireapp-1  |   File "/app/controllers/user.py", line 38, in <module>
fireapp30-backend-fireapp-1  |     class GetAvailabilitiesRequest(Resource):
fireapp30-backend-fireapp-1  |   File "/app/controllers/user.py", line 41, in GetAvailabilitiesRequest
fireapp30-backend-fireapp-1  |     def get():
fireapp30-backend-fireapp-1  |   File "/app/services/jwk.py", line 79, in requires_auth
fireapp30-backend-fireapp-1  |     wrapper.__name__ = func.__name__
fireapp30-backend-fireapp-1  | AttributeError: 'staticmethod' object has no attribute '__name__'
fireapp30-backend-fireapp-1  | [2023-08-22 12:51:00 +0000] [13] [ERROR] Exception in worker process
fireapp30-backend-fireapp-1  | Traceback (most recent call last):
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
fireapp30-backend-fireapp-1  |     worker.init_process()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 95, in init_process
fireapp30-backend-fireapp-1  |     super().init_process()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
fireapp30-backend-fireapp-1  |     self.load_wsgi()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
fireapp30-backend-fireapp-1  |     self.wsgi = self.app.wsgi()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
fireapp30-backend-fireapp-1  |     self.callable = self.load()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
fireapp30-backend-fireapp-1  |     return self.load_wsgiapp()
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
fireapp30-backend-fireapp-1  |     return util.import_app(self.app_uri)
fireapp30-backend-fireapp-1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 371, in import_app
fireapp30-backend-fireapp-1  |     mod = importlib.import_module(module)
fireapp30-backend-fireapp-1  |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
fireapp30-backend-fireapp-1  |     return _bootstrap._gcd_import(name[level:], package, level)
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
fireapp30-backend-fireapp-1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
fireapp30-backend-fireapp-1  |   File "/app/application.py", line 3, in <module>
fireapp30-backend-fireapp-1  |     from controllers import *
fireapp30-backend-fireapp-1  |   File "/app/controllers/__init__.py", line 21, in <module>
fireapp30-backend-fireapp-1  |     from .user import user_bp
fireapp30-backend-fireapp-1  |   File "/app/controllers/user.py", line 38, in <module>
fireapp30-backend-fireapp-1  |     class GetAvailabilitiesRequest(Resource):
fireapp30-backend-fireapp-1  |   File "/app/controllers/user.py", line 41, in GetAvailabilitiesRequest
fireapp30-backend-fireapp-1  |     def get():
fireapp30-backend-fireapp-1  |   File "/app/services/jwk.py", line 79, in requires_auth
fireapp30-backend-fireapp-1  |     wrapper.__name__ = func.__name__
fireapp30-backend-fireapp-1  | AttributeError: 'staticmethod' object has no attribute '__name__'
fireapp30-backend-fireapp-1  | [2023-08-22 12:51:00 +0000] [13] [INFO] Worker exiting (pid: 13)
fireapp30-backend-fireapp-1  | [2023-08-22 12:51:00 +0000] [11] [INFO] Worker exiting (pid: 11)
fireapp30-backend-fireapp-1  | [2023-08-22 12:51:00 +0000] [1] [ERROR] Worker (pid:11) exited with code 3
fireapp30-backend-fireapp-1  | [2023-08-22 12:51:30 +0000] [1] [ERROR] Shutting down: Master
fireapp30-backend-fireapp-1  | [2023-08-22 12:51:30 +0000] [1] [ERROR] Reason: Worker failed to boot.
```
